server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/users-subscriptions-db?autoReconnect=true
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
  liquibase:
    change-log: /changelog/db.changelog-master.xml
    enabled: true
  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        SQL: DEBUG
        query:
          in_clause_parameter_padding: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
springdoc:
  override-with-generic-response: false
  remove-broken-reference-definitions: false
  swagger-ui:
    displayOperationId: false
    showExtensions: true
    showCommonExtensions: true
    tags-sorter: alpha
    docExpansion: 'none'
    operations-sorter: alpha